In [1]:
# **Задание на повторение материала
# 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [22]:
import numpy as np
a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
# 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

b1 = a.reshape(3, 4)
b2 = a.reshape(2, 6)
b3 = a.reshape(4, 3)
b4 = a.reshape(6, 2)
b5 = a.reshape(12, 1)
print(b1)
print(b2)
print(b3)
print(b4)
print(b5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [28]:
# 3. Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

b1 = a.reshape(3, -1)
b2 = a.reshape(2, -1)
b3 = a.reshape(-1, 3)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 1)
print(b1)
print(b2)
print(b3)
print(b4)
print(b5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [16]:
# 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

## НЕТ ##

In [18]:
# 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального 
# распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

a = np.random.randn(3, 4)
print(a)
b = a.flatten()
print(b)

[[-1.56552118 -0.29017717 -1.62023766  0.96512505]
 [-1.56977689  1.08423041  0.2901791   0.38298483]
 [-1.02586414 -0.83700451  0.91910191 -1.33104002]]
[-1.56552118 -0.29017717 -1.62023766  0.96512505 -1.56977689  1.08423041
  0.2901791   0.38298483 -1.02586414 -0.83700451  0.91910191 -1.33104002]


In [20]:
# 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [30]:
# 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно 
# с интервалом 2. В чем разница между массивами a и b?

b = np.arange(20, 1, -2).reshape(1, 10)
print(b)

# a - это одномерный массив
# b - это двумерный массив из одной строки и 10 столбцов

[[20 18 16 14 12 10  8  6  4  2]]


In [38]:
# 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis=0)
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [50]:
# 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
# Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, 
# умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? 
# Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
print(a)
A = a.reshape(4, 3)
print(A)
At = A.transpose()
print(At)
B = A.dot(At)
print(B)
print(f"Форма B: {B.shape} , размер B: {B.size}")
print(f'Определитель d= {np.linalg.det(B)}')
# обратную матрицу вычислить не получиться, так как определитель = d = np.linalg.det(B) = 0.0, а на 0 делить нельзя.

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Форма B: (4, 4) , размер B: 16
Определитель d= 0.0


In [53]:
# 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

np.random.seed(42)

In [55]:
# 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных 
# целых чисел от 0 до 16 невключительно.

c = np.random.randint(0, 16, (16))
print(c)

[ 3 12 14 10  7 12  4  6  9  2  6 10 10  7  4  3]


In [75]:
# 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.

C = c.reshape(int(len(c)**0.5), -1)
print(C)
D = B + C * 10
print(D)
d = np.linalg.det(D)
print(f'Определитель d= {d}')
r = np.linalg.matrix_rank(D)
print(f'Ранг матрицы r= {r}')
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 3 12 14 10]
 [ 7 12  4  6]
 [ 9  2  6 10]
 [10  7  4  3]]
[[ 35 134 163 132]
 [ 84 170 126 182]
 [113 106 209 312]
 [132 192 252 332]]
Определитель d= 21320000.000000034
Ранг матрицы r= 4
[[-0.0421257  -0.04781989 -0.07423077  0.11272233]
 [ 0.00713133  0.01837899  0.00807692 -0.02050094]
 [-0.00235084 -0.03018386 -0.02807692  0.04386679]
 [ 0.01440901  0.03129456  0.04615385 -0.06324578]]


In [81]:
# 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, 
# что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, 
# используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
# получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
# для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
print(D_inv)

[[0. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 0.]]
